### PR TITLE
Added ADC and PWM typehints + ujson.

### PR DESCRIPTION
**Pull request by plugowski**
Added ujson typehint and missing method in utime.

### CODE REVIEW

**Comment by ivkond** [comment]
Bump :)

**Comment by KrasnovPavel** [comment]
Bump again

**Comment by ramsrib** [comment]
@vlasovskikh Is this gonna get reviewed/merged?  Any comments?

**Comment by mbtronics** [comment]
I would love to get this merged

**Comment by vlasovskikh** [comment]
Hi Paweł! I'm sorry that it took me ages to get back to my intellij-micropython project. Are you still interested in getting this change merged? I've reviewed it and it seems fine. I guess it's for a ESP32 device. I'd like to merge your PR and restructure it a bit to introduce explicit ESP32 support instead of just re-using code for ESP8266. Not everything that is there on ESP32 is available on ESP8266.

@plugowski Could you please electronically sign a contributor license agreement at http://www.jetbrains.com/agreements/cla/ ?

**Comment by plugowski** [comment]
Hi, yeah could be nice to merge it finally :P

**Comment by vlasovskikh** [comment]
@plugowski Just to make sure, have you signed http://www.jetbrains.com/agreements/cla/ ?

**Comment by mbtronics** [comment]
Wat part is specifically for ESP32?
I'm using the PWM class from this PR on my ESP8266, seems to be correct.
For ESP8266 there are these files: "micropython/ports/esp8266/machine_pwm.c" and  "micropython/ports/esp8266/machine_adc.c" that correspond to the PWM and ADC classes?

**Comment by vlasovskikh** [comment]
@mbtronics Parts of this PR are applicable to ESP8266 as well. However, not all the attributes added to `ADC` in the PR exist in ESP8266. Some of them are ESP32-only. I want to handle it in the plugin via a separate directory for ESP32 type hints.

**Comment by vlasovskikh** [comment]
@plugowski I'm sorry, I still haven't got your electronically signed Contributors License Agreement. Please make sure that you've signed it at http://www.jetbrains.com/agreements/cla/

**Comment by vlasovskikh** [comment]
@plugowski I'm closing this PR for now, because we haven't received the signed CLA form from you. Feel free to re-open the PR after signing the form.

**Pull request closed without merging**
