### PR TITLE
Add option to set Content Root for an upload

### PR DESCRIPTION
**Pull request by BryceBeagle**
Having the project root as the content root for an upload is not always useful. For example, if the embedded portion of the project is located in a subdirectory inside your repo.

This pull request adds an option to the Run Configuration dialog to set the Content Root. Leaving it blank will default to the Project Root, which was the previous behavior.

Note: This is my first ever public pull request. I'd appreciate any feedback you have.

### CODE REVIEW

**Comment by vlasovskikh** [comment]
@BryceBeagle I'm sorry it took me so long to review your pull request, especially your first one :(

What I especially liked about your PR:

* Your code fits nicely into the existing code base, it respects its architecture and coding style
* You took your time to document your changes for the intellij-micropython users, and the docs look easy to understand for me

I've decided to implement the ability to upload a directory as the root directory of your device in a different way, that requires less configuration and takes into account how PyCharm analyses imports statically. My approach is to use the nearest **sources** root or content root to the file or directory you want to upload.

Consider this example:

```
my_micropython_projects/  # The directory you opened in PyCharm
    project1/
        main.py
        my_lib.py
    project2/
        main.py
        ...
```

You have multiple actual projects in one directory you opened in PyCharm. In project1/ you have your main.py and you may want to use imports of local modules like my_lib.py:

main.py
```python
import utime
import my_lib  # Unresolved reference, unless you mark project1/ as a sources root

while True:
    my_lib.scan()
    utime.sleep_ms(1000)
```

Unless you mark my_micropython_projects/project1/ as a sources root via Ctrl+Click on it and "Mark Directory as | Sources Root", your import of `my_lib` will be an unresolved reference, because PyCharm won't consider it an entry on `sys.path` for resoling modules.

So my solution is that marking project1/ as the sources root makes it both available for static code analysis as a root and marks it as a root for uploading your project.

**Comment by vlasovskikh** [comment]
My solution is in commit 38ecab7c6afd7f3baece2176ee008ba14ed1f8b6.

**Comment by BryceBeagle** [comment]
I think using the nearest sources root is a much better solution. Thanks for implementing it :+1:

**Comment by vlasovskikh** [comment]
@BryceBeagle Thanks for your update! Sorry again for not reviewing your PR for such a long period, it took me ages to get back to developing this plugin.

I will release an updated version of the plugin soon. It will be compatible with PyCharm 2020.1-2020.2 due to the changes in the platform API.

**Pull request closed without merging**
