### PR TITLE
Fixed control keys in REPL on Windows 10

### PR DESCRIPTION
**Pull request by vlasovskikh**
The fix is based on the a PR to pyserial that hasn't been merged yet https://github.com/pyserial/pyserial/pull/351. I've got a permission by Cefn Hoile, the author of this PR, to use it in microrepl.py under the terms of Apache 2 license.

### CODE REVIEW

**Comment by jdjjm** [comment]
Did not work.
I tried replacing the microrepl.py in the plugin files and also building from source and both failed with the following error:

`Traceback (most recent call last):
  File "C:\Users\user\IdeaProjects\intellij-micropython\build\idea-sandbox\plugins\intellij-micropython/scripts/microrepl.py", line 197, in <module>
    main()
  File "C:\Users\user\IdeaProjects\intellij-micropython\build\idea-sandbox\plugins\intellij-micropython/scripts/microrepl.py", line 175, in main
    term = connect_miniterm(port)
  File "C:\Users\user\IdeaProjects\intellij-micropython\build\idea-sandbox\plugins\intellij-micropython/scripts/microrepl.py", line 53, in connect_miniterm
    return Miniterm(ser, echo=False)
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\serial\tools\miniterm.py", line 341, in __init__
    self.console = Console()
  File "C:\Users\user\IdeaProjects\intellij-micropython\build\idea-sandbox\plugins\intellij-micropython/scripts/microrepl.py", line 117, in __init__
    super().__init__()
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\serial\tools\miniterm.py", line 104, in __init__
    super(Console, self).__init__()
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\serial\tools\miniterm.py", line 104, in __init__
    super(Console, self).__init__()
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\serial\tools\miniterm.py", line 104, in __init__
    super(Console, self).__init__()
  [Previous line repeated 990 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
`

However, replacing line 90
`class PatchedWindows10Console(miniterm.Console):`
with
`class PatchedWindows10Console(miniterm.ConsoleBase):`
Fixed the issue and it worked. Not sure if this will produce any other issues?

Windows Version 1909
PyCharm 2020.1.2
Run on an ESP32

**Comment by vlasovskikh** [comment]
I've fixed the bug mentioned by @jdjjm. Please try again.

**Comment by jdjjm** [comment]
Latest patch now has a new error:
`Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\JetBrains\PyCharm2020.1\plugins\intellij-micropython/scripts/microrepl.py", line 196, in <module>
    main()
  File "C:\Users\user\AppData\Roaming\JetBrains\PyCharm2020.1\plugins\intellij-micropython/scripts/microrepl.py", line 171, in main
    term.console = Windows10Console()
  File "C:\Users\user\AppData\Roaming\JetBrains\PyCharm2020.1\plugins\intellij-micropython/scripts/microrepl.py", line 115, in __init__
    super().__init__()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\serial\tools\miniterm.py", line 104, in __init__
    super(Console, self).__init__()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\serial\tools\miniterm.py", line 46, in __init__
    self.byte_output = sys.stdout.buffer
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\codecs.py", line 409, in __getattr__
    return getattr(self.stream, name)
AttributeError: 'Out' object has no attribute 'buffer'
`

**Comment by jdjjm** [comment]
[Here is another working version](https://github.com/vlasovskikh/intellij-micropython/compare/fix-windows-repl...jdjjm:patch-3) based off [e880a8c patch](https://github.com/vlasovskikh/intellij-micropython/pull/105/commits/e880a8c4b5ec2bb6111890a323ab8eae5538ef46)

Let me know if this is suitable or if you want me to make a PR

**Comment by amuntobii** [comment]
version from @jdjjm works as stated for me also on Win10 pycharms 2020.1.2
Will continue testing as necessary if people keep posting patches

**Comment by vlasovskikh** [comment]
@jdjjm I've got a few comments about your version. I've created PR #106 for discussing the code.

**Comment by vlasovskikh** [comment]
@jdjjm @amuntobii Please try an updated version of microrepl.py from this PR.

**Comment by jdjjm** [comment]
This latest version worked for me. Anyone else have any success?

**Comment by vlasovskikh** [comment]
@jdjjm Thank you! Please keep using it. Do all the control keys work for you as expected? See the list of all the control keys listed in the `navcodes` variable in the diff to this PR.

@amuntobii Could you please test the current version of microrepl.py from this PR too?

**Comment by jdjjm** [comment]
The arrow keys, Home, End and delete all work as intended. The function keys all enter raw repl however, I'm not sure what their functionality is meant to be. Page Up, Page Down and Insert seem to be working as they don't fill the console with text.

  Also the console supports colour now.

**Comment by vlasovskikh** [comment]
@jdjjm Thank you! I'll wait for a while for more volunteers to test it, then I'll merge it.

**Comment by amuntobii** [comment]
works GREAT for me. this was much needed, thanks so much

**Comment by vlasovskikh** [comment]
Thank you for testing it! I'm merging it to master.

**Pull request merged**
