### PR TITLE
Minimal Raspberry Pi Pico support

### PR DESCRIPTION
**Pull request by lwr20**
Relates to #132

### CODE REVIEW

**Comment by lwr20** [comment]
Raising as draft PR to allow early feedback.  As I'm extremely new to this (pycharm plugins, micropython, etc), I figure I need all the feedback I can get :)

**Comment by whi-tw** [comment]
So, with my limited testing (writing and uploading a blinky hello-world) it's working A-OK at the moment

**Comment by whi-tw** [comment]
Unsure where the remit of this PR ends and other things start, but the blink w/ timer sample code has a few incorrect function parameter definitions, particularly `timer.init` doesn't understand `freq`.

https://github.com/raspberrypi/pico-micropython-examples/blob/master/blink/blink.py#L1-L9

**Comment by lensvol** [comment]
Maybe we should consider `machine.pyi` as board-specific and put different versions of it into appropriate directories?

**Comment by lwr20** [comment]
> Maybe we should consider machine.pyi as board-specific and put different versions of it into appropriate directories?

That's definitely an option.  Of course this means a fair amount of code repetition which is _usually_ a bad idea, maybe its OK in this circumstance since the exact version of micropython on the boards is controlled by repos outside of this one.

If we're doing that, I'd really want to find a way to auto-generate typehints from the board-specific repos rather than recreating them for every board.  MonkeyType looks interesting in that direction: https://instagram-engineering.com/let-your-code-type-hint-itself-introducing-open-source-monkeytype-a855c7284881

**Comment by lensvol** [comment]
MonkeyType indeed looks promising, but here we have a very special edge case: different interpreters with slightly different codebase and that are intended to run on completely different machines. While manual type hint creation will involve a noticeable amount of work upfront, MicroPython standard library does not change _that_ much, and maintaining it IMHO will be easier in the long run.

We should also investigate if it is possible to "override" specific type hint in the board-specific directories.

**Comment by whi-tw** [comment]
@vlasovskikh, what are your thoughts on how best to handle the various different board types and their idiosyncrasies?

**Comment by b-errouane** [comment]
Should this problem really be handled in this PR? For me it looks like this is a general problem with the current structure of the typehints in this project. Sure it does manifest itself in this PR because (if I understand it correctly) with the pico there is yet another implementation of the MicroPython library. But as @whi-tw stated, the problem already exists in the master branch because of differences between esp8266 and pyboard (if I got that right).

Getting Pi Pico support into the master branch should also help with popularity of this project because AFAIK the main contender is Thonny which is nice and all, but nothing compared to having IntelliJ as an IDE.

**Comment by lwr20** [comment]
@b-errouane I'm inclined to agree with you.  If we think this PR on its own represents a useful increment, maybe it should be merged and we make further improvements (to typehints) in subsequent PRs?

**Comment by lwr20** [comment]
There are stubs here: 
https://github.com/cpwood/Pico-Go/tree/main/stubs
GPL3 licensed.

**Comment by lensvol** [comment]
@lwr20 Thank you for this!

At this moment, we have your PR and https://github.com/vlasovskikh/intellij-micropython/pull/143 by @timsavage. They are almost identical, but their PR also has some rudimentary typehints for `rp2` included.

What would you say if that PR got merged, but you both will be credited in the relevant documentation for the work you've done?

**Comment by lensvol** [comment]
Regarding `PicoGo` typehint stubs: I am not sure we can use them here since they are licensed under GPL3 and this project uses Apache 2 License. According to the [official statement](https://www.apache.org/licenses/GPL-compatibility.html), they are incompatible. :( 

A better way IMO will be to recreate them via clean room reverse engineering the C++ SDK and existing Python SDK documentation.

We are also thinking about how to properly accommodate differences between MicroPython standard libraries on various boards, hopefully it will be more clear going forward.

**Comment by lwr20** [comment]
> What would you say if that PR got merged, but you both will be credited in the relevant documentation for the work you've done?

I'm not worried about credit here - so long as this support gets added, I'll be happy :)  His PR is clearly more complete, just merge his, I'll close this one now.

> since they are licensed under GPL3 

Ah rats - I missed that license issue.  Yes, that is a problem and agree it will require a clean room implementation.

**Pull request closed without merging**
