### PR TITLE
Support for raspberry pi pico

### PR DESCRIPTION
**Pull request by timsavage**
Adds support for the Raspberry Pi Pico board.

- Is autodetected via its USB identifiers
- REPL works
- Uploading files works

Type hints are "best effort" at this point, I have reverse engineered what I could from the available documentation and poking about in the REPL. These API's are also under development, even the official docs are not always correct.

Covers #132

### CODE REVIEW

**Comment by TheCatster** [comment]
Any reason why this hasn't been merged yet? Seems to provide all basic necessary features.

**Comment by lensvol** [comment]
> Any reason why this hasn't been merged yet? Seems to provide all basic necessary features, and looks good.

I will give it once-over and check with my Pico in a couple of days. Sorry for the long delay, only got some spare time back recently.

**Comment by TheCatster** [comment]
> Sorry for the long delay, only got some spare time back recently.

Completely understand that! Was just curious to see if there was a major issue here or not. Thanks!

**Comment by lensvol** [comment]
I have verified that it works with my "vanilla" Raspberry Pi Pico.

Thank you for helping with this!

**Comment by lensvol** [comment]
@timsavage I haven't checked that you signed the CLA before merging. :( 

I'll have to revert until I get the confirmation that it has been signed. Sorry for the hassle!

**Comment by timsavage** [comment]
@lensvol Let me know what needs to be signed off, happy to do that.

**Comment by lensvol** [comment]
@timsavage Could you please visit https://www.jetbrains.com/agreements/cla/ and electronically sign the contributor license agreement? After that PR will be marked as "CLA Signed" and I will re-introduce your changes into the codebase. :)

I apologize for the inconvenience.

**Review by vlasovskikh — COMMENTED** [review]
Looks good to me!

**Comment by vlasovskikh** [comment]
@lensvol BTW Do you think we should add "Make sure you've signed the CLA" step with the comment on how to do it to our Source Code section of the README.md?

**Comment by timsavage** [comment]
Have signed the CLA.

**Comment by timsavage** [comment]
Have signed the CLA

**Comment by vlasovskikh** [comment]
@timsavage Thank you!

**Comment by lensvol** [comment]
> @lensvol BTW Do you think we should add "Make sure you've signed the CLA" step with the comment on how to do it to our Source Code section of the README.md?

Yes, alongside with "Please check if there is already a pull request that solves the same problem". We've had quite a few duplicate ones recently, would not hurt to explicitly mention this as well.

In addition to updating `README.md` we can also make a template for the pull request with a similar checklist. :)

**Pull request merged**
