### PR TITLE
microbit: Update uFlash to include micro:bit MicroPython v1.0

### PR DESCRIPTION
**Pull request by carlosperate**
This version of micro:bit MicroPython adds support for the change in motion sensors.

Btw, thanks for walking me through the plugin development process during EuroPython, it was very useful when testing this.

Happy new year and prosperous 2019!

### CODE REVIEW

**Comment by fzymek** [comment]
Please merge this. It gave me a headache to figure out why my code was not working when using accelerometer

**Comment by ItsThatBlackKid** [comment]
Can you please merge this branch? its giving me a headache working with your plugin

**Comment by vlasovskikh** [comment]
@carlosperate Hi Carlos! Sorry it took me ages to get back to my intellij-micropython project. Merging your PR now. Thank you!

**Comment by carlosperate** [comment]
No worries, thanks for taking the time to work on this project again!

**Pull request merged**
