### PR TITLE
Adds to scripts

### PR DESCRIPTION
**Pull request by MrYsLab**
Added microfs and uflash to scripts. Note that microfs requires command line parameters to specify the action: ls, put, get, remove and also a file name for put, get and remove.

### CODE REVIEW

**Comment by MrYsLab** [comment]
I just added a feature to pseudo-microbit that minifies the python source files (removes comments and unnecessary white space). I am using pyminifier to do this. It takes the original file and creates a new minified file while leaving the original untouched. I am not sure is you wish to add this also.

The command I am using pyminifier -o pyfile_min.py pyfile.py

The tool may be found here: https://github.com/liftoff/pyminifier

It consists of several scripts.

**Comment by vlasovskikh** [comment]
@MrYsLab Could you explain the idea behind this pull request please? Is it a step towards integrating these scripts into the plugin? Are these scripts intended to be invoked via external actions?

**Comment by MrYsLab** [comment]
Yes, having these as being part of the plugin would be helpful. I have added them as external tools and find it convenient not to have to open a terminal window to invoke them. I am not sure the best way to integrate them, but external tools might be a good choice.

It might be useful move the flash operation from the right-click context menu on a file as an external tool as well. I often work with both PC Python files and micro:bit Python files in the same project. Having to turn the plugin off and on to either run a PC file or to flash a micro:bit file slows down my workflow. My preference would be to have the plugin enabled to do type hinting, but not affect the external tools.

**Comment by vlasovskikh** [comment]
@MrYsLab Integrating a minifier could be a good extra option. Please consider adding a new feature request about it.

**Comment by vlasovskikh** [comment]
@MrYsLab I believe both `microfs` and `uflash` are available on PyPI. The MicroPython plugin for PyCharm has a mechanism for asking the user to install the packages required for plugin operations: see [this piece of code](https://github.com/vlasovskikh/intellij-micropython/blob/master/src/main/kotlin/com/jetbrains/micropython/devices/MicroBitDeviceProvider.kt#L42).

`uflash` is already listed there since the plugin uses it to upload Python files to the Micro:bit.

As for `microfs` and file system operations, the IntelliJ platform behind PyCharm has a concept of virtual file systems in its API. They allow creating file systems that are not very different from your disk file system, but have some custom logic for accessing files. I believe we can try to implement such a file system based on `microfs`. From the users' perspective, it could be a tool window for browsing the contents of your device. I'm not sure about opening files from the device for editing (`get` followed by `put`), but at least it will be useful as an overview and the means to delete files. @MrYsLab If you like this idea, feel free to file a feature request about it.

I'm closing this PR, since these tools can be provided as dependencies and they are available on PyPI. Anyway, thanks for your ideas. Please file feature separate feature requests about them.

**Pull request closed without merging**
