### PR TITLE
Create `uarray.pyi`.

### PR DESCRIPTION
**Pull request by hlovatt**
From: from https://github.com/hlovatt/PyBoardTypeshed.
Generated by: https://github.com/hlovatt/PyBoardTypeshedGenerator.

### CODE REVIEW

**Review by vlasovskikh — APPROVED** [review]
Thanks @hlovatt for sending your PR! I'll merge it as is with a small change I'll make: move it to typehints/stdlib. The stub is not complete though. It misses `__getitem__` for the  `myarray[i]` syntax. It's not there in `dir(array)`. I guess this is the reason your stub generator didn't pick it up. But without this `__getitem__` PyCharm will complain about [] being an incorrect operation on arrays. I hope future PRs from you or other people will make this stub (and others) better! :)

**Comment by vlasovskikh** [comment]
@hlovatt You might also want to take a look at the stub for the regular `array.array` as a source of inspiration how to restrict the `typecode` and how to express the dependency between the `iterable` you pass to your `__init__` and the value you get from `__getitem__`.

**Comment by vlasovskikh** [comment]
@hlovatt Here's the link to `array.array` in Typeshed: https://github.com/python/typeshed/blob/master/stdlib/2and3/array.pyi#L19

**Comment by hlovatt** [comment]
Thanks for all the suggestions. Will make an improved version. You are correct in that there is a problem with scraping the MicroPython docs in that they aren’t complete. Also many ‘in built’ items like `__getitem__` don’t show up with `dir` etc. I can add manually. 

With respect to `uarray` I have already corrected the MicroPython doc with `__getitem__`  etc. and submitted to them a pull request. However, they have accepted yet. But I can manually add in mean time. 

-- Howard.

**Pull request merged**
