### PR TITLE
Create `pyb.pyi`.

### PR DESCRIPTION
**Pull request by hlovatt**
From: https://github.com/hlovatt/PyBoardTypeshed.
Generated by: https://github.com/hlovatt/PyBoardTypeshedGenerator.

### CODE REVIEW

**Review by vlasovskikh — APPROVED** [review]
@hlovatt This stub file looks very impressive! Thank you for contributing it! I like how you added docs from the corresponding *.rst via your rst2pyi.py. Is pyb.py in your Generator project something that you've created manually or automatically?

Your stub covers lots of things. I haven't checked all the methods and I just looked at the general style of your definitions and how it reflected the structure of [the pyb docs](https://docs.micropython.org/en/latest/library/pyb.html). If there are any missing methods or bugs in type hints, I'm sure future pull requests by contributors will make things more correct eventually :)

**Comment by vlasovskikh** [comment]
@hlovatt You might be interested in how I added `pyb` to be available for code insight if your device type is "Pyboard" in the MicroPython settings in PyCharm: see the corresponding commit 138fcee18da1f0339f9f739f0445afc29a1e362e. It's really a one-line change.

**Comment by hlovatt** [comment]
Thanks. Unfortunately I had to write pyb.py manually :(
  -- Howard.

**Comment by vlasovskikh** [comment]
This PR fixes most of the issues mentioned #16.

**Comment by vlasovskikh** [comment]
> Thanks. Unfortunately I had to write pyb.py manually :( -- Howard.

Ouch... That's a huge amount of work. Thanks for working on this!

**Pull request merged**
